build:
  correctness:
    test-data-loader:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run //:typedb-extractor -- dist/typedb-all-linux
        sudo systemd-run ./dist/typedb-all-linux/typedb server
        sleep 60
        bazel test //:data-loader-test --test_output=errors